### ISSUE TITLE
Extract Review Fails due to max 16 local views opened

### ISSUE THREAD

**Issue by LiborBatek** [ynput/ayon-blender#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When trying to publish ```Review``` it can fail due to multiple views present in active workfile the publish happens from.

![image](https://github.com/user-attachments/assets/e9cc88da-bee8-4d3b-a1e1-09c1b06f8065)

This seems to happen after mutliple publishes happened in past (15x times plus) from the same workfile...this is just my guess looking on the error shown...

### Expected Behavior:

User have to be able to produce unlimited amount of publishes speaking of any product type including ```Review``` one. Now this not being the case and Ayon fails due to ```Blender``` policies...

We have to ensure / force blender to not produce those unnecessary views or shut those down aka close those viewports.

```
Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "C:\Work\REPO\ayon-blender\client\ayon_blender\plugins\publish\extract_playblast.py", line 89, in process
    path = capture(**preset)
           ^^^^^^^^^^^^^^^^^
  File "C:\Work\REPO\ayon-blender\client\ayon_blender\api\capture.py", line 87, in capture
    applied_view(window, camera, isolate, options=display_options)
  File "C:\Work\REPO\ayon-blender\client\ayon_blender\api\capture.py", line 159, in applied_view
    isolate_objects(window, isolate or objects)
  File "C:\Work\REPO\ayon-blender\client\ayon_blender\api\capture.py", line 132, in isolate_objects
    bpy.ops.view3d.localview()
  File "C:\Work\REPO_SW\DCC\BLENDER\4.2.0\WINDOWS\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: No more than 16 local views
```

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Create ```Review``` publish instance\
2. Publish Review 15+ times (versions up to v016)
3. After those it should start failing due to many viewports left opened

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by LiborBatek** [comment]
been avoided already...wont happen anymore, so closing as resolved.
