### ISSUE TITLE
Deadline submission script collides with Ayon

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/ayon-blender#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

After installing Deadline submitter, it is not working when Blender is launched via Launcher and using Ayon environments.

When launched without Ayon, everything works as expected

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

- Install Deadline submitter addon to Blender
- Launch Blender via Launcher
- Render -> Submit to Deadline

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
qt.qpa.window: SetProcessDpiAwarenessContext() failed: The operation completed successfully.
Qt's default DPI awareness context is DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2. If you know what you are doing, you can overwrite this default using qt.conf (https://doc.qt.io/qt-6/highdpi.html#configuring-windows).
Registered font families: Noto Sans, Noto Sans, Noto Sans, Noto Sans, Noto Sans Mono Black, Noto Sans Mono, Noto Sans Mono ExtraBold, Noto Sans Mono ExtraLight, Noto Sans Mono Light, Noto Sans Mono Medium, Noto Sans Mono, Noto Sans Mono SemiBold, Noto Sans Mono Thin
Read blend: "C:\projects\murphyAyonFtrack\assets\myChar\work\modeling\maf_myChar_modeling_v006.blend"
Appending "C:/Users/murph/Documents/Ayon/REPO_SW/DEADLINE10/submission/Blender/Main" to system path to import SubmitBlenderToDeadline module
Info: Saved "maf_myChar_modeling_v006.blend"
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Python.Runtime.Runtime.PyObject_CallObject(Python.Runtime.BorrowedReference, Python.Runtime.BorrowedReference)
   at Python.Runtime.ImportHook.SetupImportHook()
   at Python.Runtime.ImportHook.Initialize()
   at Python.Runtime.Runtime.Initialize(Boolean)
   at Python.Runtime.PythonEngine.Initialize(System.Collections.Generic.IEnumerable`1<System.String>, Boolean, Boolean)
   at Python.Runtime.PythonEngine.Initialize(Boolean, Boolean)
   at Python.Runtime.PythonEngine.Initialize()
   at FranticX.Scripting.PythonNetScriptEngine.Initialize(Boolean, System.String, System.String)
   at FranticX.Scripting.PythonNetScriptEngine..ctor(Boolean, Boolean, System.String, System.String)
   at Deadline.Scripting.DeadlineScriptManager.a()
   at Deadline.Scripting.DeadlineScriptManager..ctor(Deadline.Controllers.DataController, Boolean, Boolean)
   at Deadline.Scripting.DeadlineScriptManager.GetInstance(Deadline.Controllers.DataController, Boolean, Boolean)
   at Deadline.Applications.Consoles.DeadlineRepositoryUICommand.a(Boolean, Boolean)
   at Deadline.Applications.Consoles.DeadlineRepositoryUICommand.RequestScriptManager(Boolean, Boolean)
   at Deadline.Applications.Consoles.ExecuteScript.Invoke(System.String[])
   at FranticX.Applications.Consoles.ConsoleCommandInvoker.InvokeCommand(System.String[], System.Type)
   at FranticX.Applications.Consoles.ConsoleCommandInvoker.InvokeCommand(System.String[])
   at Deadline.Submission.Submit.Perform(System.String[])
   at DeadlineCommand.DeadlineCommandAppStartup.Main(System.String[])
```

**Comment by LiborBatek** [comment]
@m-u-r-p-h-y do we really care about ```AWS Deadline submitter``` as we have own solution? maybe we can close this one, no?
