### ISSUE TITLE
Extract Animation (FBX) not working and fails with error

### ISSUE THREAD

**Issue by LiborBatek** [ynput/ayon-blender#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When having ```Animation``` publish instance type present and want to publish ```FBX``` repre (optional) it fails and gives following error:

```
DEBUG: Performing extraction..
Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\pyblish\plugin.py", line 528, in __explicit_process
    runner(*args)
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.3\ayon_blender\plugins\publish\extract_fbx_animation.py", line 125, in process
    original_name = armature_name.split(':')[1]
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

### Expected Behavior:

Animation product should also work not only with Alembic but also with ```FBX``` repre type.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1.Load some rig and animate it
2.Create ```Animation``` publish instance
3. Enable ```FBX``` optional flag for extracting FBX too
4. Publish will fail due to the error

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by sosoyan** [comment]
I bumped into this recently and pushed a quick fix here, can PR if it helps.
https://github.com/sosoyan/ayon-blender/commit/27a9b310533c2a66b6e24bc034d0e1fe25760ff7
