### ISSUE TITLE
Publishing "Action" product produces empty .blend file

### ISSUE THREAD

**Issue by LiborBatek** [ynput/ayon-blender#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When trying to publish ```Action``` product type it produces empty data (.blend file) and its not possible to load anything.

Also throw an error when trying perform ```AYON > Load``` on the ```Action``` product

```
Traceback (most recent call last):

  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.3\ayon_blender\api\ops.py", line 128, in execute
    result = callback(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.3\ayon_blender\api\plugin.py", line 495, in _load
    nodes = self.process_asset(
            ^^^^^^^^^^^^^^^^^^^

  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.3\ayon_blender\plugins\load\load_action.py", line 77, in process_asset
    collection.children.link(bpy.data.collections[lib_container])
                             ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^

KeyError: 'bpy_prop_collection[key]: key "sh010_actionMain" not found'
```

Probably due to been empty and not containing any data??

### Expected Behavior:

When producing ```Action``` via publishing it should output .blend file containing ```Action``` data type inside and user should be able to load such data via AYON Loader later on.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. Load some rig
2. Animate it
3. Create ```Action``` publish instance
4. Publish will produce unusable (empty) .blend file

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by LiborBatek** [comment]
@moonyuet we should also do something about this one... either remove/hide the creator or introduce some kind of workflow using these (Im all for the later option to introduce functional workflow around it)

**Comment by LiborBatek** [comment]
Cool, it would be best to have loader for ```Action``` product which would bring it into the workfile and add Fake user so it could stay intact while saving and re-opening the scene even if not assigned to any object. 

I think the cool thing about this publish isntance type "Action" is it could be extracted from any sort of object with existing action, not just ```Rig``` type which have Armature node and then reconnected back to loaded products opening a lot of possibilities for anim workflows. Now the question is if we would like to build a full versioning/management around this (with e.g. "connect Action to selection" action etc) or leave it to just simple "Extract > Load " type of workflow so the user might be able to just extract from animated "rig" product type and simply load it into the active workfile and then hook it manually to something and if load it again it would simply bring another one with added padded number (as normally when duplicate something in blender)

Maybe going just for the later "simple" workflow might do... so it just extracts and work as expected.
