### ISSUE TITLE
Deadline submission is broken after refactoring for JobInfo

### ISSUE THREAD

**Issue by kalisp** [ynput/ayon-blender#81]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior
```
Traceback (most recent call last):
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\core_1.0.10\ayon_core\pipeline\publish\lib.py", line 451, in filter_pyblish_plugins
    plugin.apply_settings(project_settings)
  File "C:\Users\lbate\AppData\Local\Ynput\AYON\addons\blender_0.2.6\ayon_blender\plugins\publish\collect_file_dependencies.py", line 19, in apply_settings
    settings = project_settings[ "deadline"]["publish"]["BlenderSubmitDeadline" ]  # noqa
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyERROR: 'BlenderSubmitDeadline'
```

## Expected Behavior
Shouldnt fail, BlenderSubmitDeadline was removed from Setting, needs to be replaced by content from `instance.data["deadline"]["job_info"]`

### Version
Occurs when using https://github.com/ynput/ayon-deadline/releases/tag/0.5.0

### Relevant log output:

```shell

```

**Comment by BigRoy** [comment]
Should be fixed by https://github.com/ynput/ayon-blender/pull/123
